// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserId_en_Seller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserId_en_Seller));
        
        string IMigrationMetadata.Id
        {
            get { return "201605052153538_UserId_en_Seller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
